name: Testing classes

on:
  - pull_request

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up conda environment
        run: conda env create -f ./environment.yml
      - name: Running unit tests
        run: |
          cd src/
          $CONDA/envs/data_structures/bin/python -m unittest discover -v -s tests
